###### directory where results will be written
output_dir: ./results/

###### experiment & trial time limit in seconds (20 hours / 3 hours)
experiment_time_limit: 72000
trial_time_limit: 10800


###### number of trials for hyperparameter search & optimization
n_random_trials: 3
n_opt_trials: 100
hparam_seed: 0

###### GPU parameters
use_gpu: False
gpu_ids: [0]
data_parallel: True

###### Training parameters
batch_size: 128
val_batch_size: 256
early_stopping_rounds: 20
epochs: 100
logging_period: 100
scale_numerical_features: None