###### i/o
output_dir: ./unittests/results/
write_predictions: True

###### experiment & trial time limit in seconds (10 hours / 2 hours)
experiment_time_limit: 36000
trial_time_limit: 7200


###### number of trials for hyperparameter search & optimization
n_random_trials: 2
n_opt_trials: 0
hparam_seed: 0

###### GPU parameters
use_gpu: False
gpu_ids: [0]
data_parallel: True

###### Training parameters
batch_size: 128
val_batch_size: 256
early_stopping_rounds: 20
epochs: 2
logging_period: 100

###### Preprocessing of numerical features
scale_numerical_features: Quantile